### PR TITLE
Nikola/reown update

### LINKED ISSUE #1264: Reown fails in iOS if connected network is not Sepolia and tries to switch
**Describe the bug**
If the network that you have in Metamask is not Sepolia, and you connect with Reown, it will try to switch to Sepolia but it fails

**Steps**
1. Build in iOS
2. Connect with Reown
3. Connect with Metamask
4. Sign message in Metamask
5. Go back to Unity app
6. It will switch you back to Metamask
7. Nothing happens in Metamask
8. Go back to Unity app

**Expected behavior**
Network is switched to Sepolia

**Console errors**
```
Web3Exception: HTTP.POST to ‘https://rpc.walletconnect.com/v1?chainId=eip155:8333&projectId=f4bff60eb260841f46b1c77588cd8acb’ responded with error: {“status”:“FAILED”,“reasons”:[{“field”:“chainId”,“description”:“We don’t support the chainId you provided: eip155:8333. See the list of supported chains here: https://docs.walletconnect.com/cloud/blockchain-api#supported-chains”}]}
 at ChainSafe.Gaming.Web3.Core.Unity.UnityHttpClient.UnityWebRequestToNetworkResponse (UnityEngine.Networking.UnityWebRequest request) [0x00000] in <00000000000000000000000000000000>:0
 at ChainSafe.Gaming.Web3.Core.Unity.UnityHttpClient+<>c__DisplayClass3_0.<PostRaw>b__0 () [0x00000] in <00000000000000000000000000000000>:0
 at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0
 at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () [0x00000] in <00000000000000000000000000000000>:0
 at IEnumeratorAwaitExtensions+InstructionWrappers+<ReturnSelf>d__2`1[T].MoveNext () [0x00000] in <00000000000000000000000000000000>:0
 at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0
--- End of stack trace from previous location where exception was thrown ---
**Screenshots/Video**
If applicable, add screenshots or screen recordings that help visualize the issue.
```

**Mobile (please complete the following information):**
 - Chainsafe SDK version: [dev]
 - Platform: [iOS]
 - Device Type: [Real device]
 - OS Version: [latest]

### PR DESCRIPTION
**Pull request by kantagara**
This should close #1264 

No documentation update needed.

### CODE REVIEW

**Review by sneakzttv — APPROVED** [review]

File: Packages/.gitignore [hunk 1]
```diff
@@ -78,14 +78,9 @@ crashlytics-build.properties
 # meta files are ignored in the root gitignore, negate that here
 !*.meta
 
-# Ignore the build artifacts from our libraries
-/io.chainsafe.web3-unity/Runtime/Libraries/*.dll
```
Comment (rob1997) [inline Packages/.gitignore:82]: why the removal? is CI failing?

File: Setup/SyncDependencies.cs [hunk 2]
```diff
@@ -62,6 +62,12 @@ public void Run()
             foreach (string name in namespaces)
             {
                 string fileSource = Path.Combine(source, $"{name}.dll");
+
+                if (!Path.Exists(fileSource))
```
Comment (rob1997) [inline Setup/SyncDependencies.cs:66]: This would mean the DLL in `dependencies,.json` isn't generated in `ChainSafe.Gamming.Unity` shouldn't it throw an exception?

Comment (kantagara) [reply Setup/SyncDependencies.cs:66]: You are right. I have added it for testing something, will remove this

File: Packages/.gitignore (hunk 1 above)
Comment (kantagara) [reply Packages/.gitignore:82]: No I needed a specific dll to be inside of the git source control :D
